Repository BuildForSDG/Teachers-Hub-Backend, pull requests merged in 2020-05, with the labels that each got.

#33 fix failing login validation
  src/users/controller.py
  src/users/view.py
  src/validators/user_validator.py
Labels: bug

#29 An administrator should be able to delete a course
  .gitignore
  requirements.txt
  src/courses/controller.py
  src/courses/view.py
Labels: Backend, enhancement

#30 a user should be able to view a single course
  .gitignore
  src/courses/view.py
Labels: Backend, enhancement

#31 admin should be able to update a course
  README.md
  src/courses/controller.py
  src/courses/view.py
Labels: Backend, enhancement

#40 Ft view all courses
  src/courses/controller.py
  src/courses/view.py
Labels: Backend
